### ISSUE TITLE
still viable?

### ISSUE THREAD

**Issue by vjcitn** [mtmorgan/TENxGenomics#15]
if not maybe put a pointer at top of README

Installing github package(s) ‘mtmorgan/TENxGenomics’
Downloading GitHub repo mtmorgan/TENxGenomics@master
from URL https://api.github.com/repos/mtmorgan/TENxGenomics/zipball/master
Installing TENxGenomics
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/5_/14ld0y7s0vbg_z0g2c9l8v300000gr/T/RtmpZ1fGvz/devtools118ef71231fe6/mtmorgan-TENxGenomics-431dff7'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests 

* installing *source* package ‘TENxGenomics’ ...
** R
** preparing package for lazy loading
Error in setMethod("subset_seed_as_array", "TENxMatrixSeed", .subset_TENxMatrixSeed_as_array) : 
  no existing definition for function ‘subset_seed_as_array’
Error : unable to load R code in package ‘TENxGenomics’
ERROR: lazy loading failed for package ‘TENxGenomics’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/TENxGenomics’
Installation failed: Command failed (1)
Old packages: 'descr', 'digest', 'mgcv'

> sessionInfo()
R Under development (unstable) (2017-12-28 r73968)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.29.3 rmarkdown_1.8       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14    digest_0.6.13   withr_2.1.1     rprojroot_1.3-2
 [5] R6_2.2.2        backports_1.1.2 git2r_0.21.0    magrittr_1.5   
 [9] evaluate_0.10.1 httr_1.3.1      stringi_1.1.6   curl_3.1       
[13] devtools_1.13.4 tools_3.5.0     stringr_1.2.0   compiler_3.5.0 
[17] memoise_1.1.0   htmltools_0.3.6 knitr_1.18     
>

**Comment by LTLA** [comment]
The _DropletUtils_ package just went into BioC-devel, which might be a more stable home for __some__ of the code in _TENxGenomics_. (I'm thinking of only the code required to convert it to a `HDF5Matrix`, to avoid having to drag in the implementation of the `TENxMatrix` and `TENxSummarizedExperiment` classes; those seem like a big maintenance overhead for just one resource.)

**Comment by mtmorgan** [comment]
I (thanks @hpages) updated TENxGenomics to be functional again; I don't intend for it ever to be submitted.
